logging:
  level: "INFO"

rfdmovie:
  postgresql:
    host: "127.0.0.1"
    port: 35332
    user: "postgres"
    password: ""
    db_name: "rfdmovie"
    check_interval: 60
  sqlalchemy:
    echo: False

movie_heaven:
  base: "http://s.dydytt.net/"
  search: "http://s.dydytt.net/plus/search.php?kwtype=0&keyword="

douban:
  search: "https://movie.douban.com/subject_search?cat=1002&search_text="
